#!/usr/bin/env bash
#
# predeploy-python.sh — runs before every deploy of the python functions
# codebase (wired up in firebase.json).
#
# Two jobs:
#   1. Stamp the git sha into functions-python/parser_version.py, so the data a
#      deploy produces records which code produced it. The Goa column bug
#      reached production because the fix for the PREVIOUS data bug was
#      committed 2026-07-25 while the live revision was still 2026-07-23, and
#      nothing in Firestore could reveal the gap.
#   2. Run the golden parser tests. They caught the Goa offset immediately once
#      run — the problem was that running them was a manual step nobody owed.
#
# The fixtures (timetable-*.pdf) are gitignored admin inputs, so the suite skips
# itself when they are absent. That means this hook is a real gate on the
# maintainer's machine and a no-op on a clean checkout. It does NOT block the
# deploy when the venv or the PDFs are missing — a hook that cannot run its
# check must not pretend the check passed, so it says so loudly instead.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_FILE="$ROOT/functions-python/parser_version.py"

sha="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if ! git -C "$ROOT" diff --quiet HEAD -- functions-python 2>/dev/null; then
  sha="$sha-dirty"
fi

cat > "$VERSION_FILE" <<EOF
# Generated by scripts/predeploy-python.sh — do not edit, do not commit.
PARSER_VERSION = "$sha"
EOF
echo "[predeploy] parser version: $sha"

PY="$ROOT/functions-python/venv/bin/python"
if [ ! -x "$PY" ]; then
  echo "[predeploy] WARNING: $PY not found — golden parser tests NOT run."
  exit 0
fi

echo "[predeploy] running golden parser tests..."
"$PY" "$ROOT/functions-python/test_timetable_parsers.py"
